// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvtFihYgO-EOQfU1vw8DNFk46tzfl-74',
    appId: '1:693176023275:web:0672208c7884da9f0226ae',
    messagingSenderId: '693176023275',
    projectId: 'water-quality-measuring-6f7aa',
    authDomain: 'water-quality-measuring-6f7aa.firebaseapp.com',
    databaseURL: 'https://water-quality-measuring-6f7aa-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-measuring-6f7aa.appspot.com',
    measurementId: 'G-94KPXFJC8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDSiPxgnVl8zBjkA_UsgWZNUkuS-Ym_I',
    appId: '1:693176023275:android:00c04e27ad47b9ff0226ae',
    messagingSenderId: '693176023275',
    projectId: 'water-quality-measuring-6f7aa',
    databaseURL: 'https://water-quality-measuring-6f7aa-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-measuring-6f7aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZjKVZu8xLfO6Yk1qyQ2_-sQiaLeb0Ug',
    appId: '1:693176023275:ios:75e8ea42462f53b50226ae',
    messagingSenderId: '693176023275',
    projectId: 'water-quality-measuring-6f7aa',
    databaseURL: 'https://water-quality-measuring-6f7aa-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-measuring-6f7aa.appspot.com',
    iosBundleId: 'com.example.hydrolinkTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZjKVZu8xLfO6Yk1qyQ2_-sQiaLeb0Ug',
    appId: '1:693176023275:ios:3a7271d42c902f7c0226ae',
    messagingSenderId: '693176023275',
    projectId: 'water-quality-measuring-6f7aa',
    databaseURL: 'https://water-quality-measuring-6f7aa-default-rtdb.firebaseio.com',
    storageBucket: 'water-quality-measuring-6f7aa.appspot.com',
    iosBundleId: 'com.example.hydrolinkTesting.RunnerTests',
  );
}
